//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\P41608\Google Drive\FHHAGENBERG\FE\SPA\Demos\DSL\StructuredEntityInteractionDescriptionLanguage\Grammar\Seidl.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Seidl.Tools {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SeidlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ISeidlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] SeidlParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] SeidlParser.SetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] SeidlParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SeidlParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SeidlParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.atomictype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomictype([NotNull] SeidlParser.AtomictypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.complextype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplextype([NotNull] SeidlParser.ComplextypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] SeidlParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.variablelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariablelist([NotNull] SeidlParser.VariablelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.typedvariablelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedvariablelist([NotNull] SeidlParser.TypedvariablelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.expressionlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionlist([NotNull] SeidlParser.ExpressionlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SeidlParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.arraydeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraydeclaration([NotNull] SeidlParser.ArraydeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.arrayaccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayaccess([NotNull] SeidlParser.ArrayaccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.fieldaccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldaccess([NotNull] SeidlParser.FieldaccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.lefthandside"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLefthandside([NotNull] SeidlParser.LefthandsideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.importstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportstatement([NotNull] SeidlParser.ImportstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.functiondefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctiondefinition([NotNull] SeidlParser.FunctiondefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.functionbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionbody([NotNull] SeidlParser.FunctionbodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.returnstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnstatement([NotNull] SeidlParser.ReturnstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctioncall([NotNull] SeidlParser.FunctioncallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.recorddefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecorddefinition([NotNull] SeidlParser.RecorddefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.graphdefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraphdefinition([NotNull] SeidlParser.GraphdefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.nodedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodedefinition([NotNull] SeidlParser.NodedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.edgedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdgedefinition([NotNull] SeidlParser.EdgedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] SeidlParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] SeidlParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.functiontype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctiontype([NotNull] SeidlParser.FunctiontypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.recordtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecordtype([NotNull] SeidlParser.RecordtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.graphtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraphtype([NotNull] SeidlParser.GraphtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.nodetype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodetype([NotNull] SeidlParser.NodetypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.edgetype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdgetype([NotNull] SeidlParser.EdgetypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SeidlParser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminator([NotNull] SeidlParser.TerminatorContext context);
}
} // namespace Seidl.Tools
