//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\dev\workspaces\spa\Sidl\src\Grammar\SidlParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Sidl.Processor {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SidlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ISidlParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] SidlParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] SidlParser.SetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>terminatorStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminatorStatement([NotNull] SidlParser.TerminatorStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>scopeStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScopeStatement([NotNull] SidlParser.ScopeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>declarationStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] SidlParser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assignmentStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentStatement([NotNull] SidlParser.AssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>definitionStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinitionStatement([NotNull] SidlParser.DefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>structDefinitionStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDefinitionStatement([NotNull] SidlParser.StructDefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>messageDefinitionStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageDefinitionStatement([NotNull] SidlParser.MessageDefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nodetypeDefinitionStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodetypeDefinitionStatement([NotNull] SidlParser.NodetypeDefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nodeDefinitionStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodeDefinitionStatement([NotNull] SidlParser.NodeDefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>metaDefinitionStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetaDefinitionStatement([NotNull] SidlParser.MetaDefinitionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>importStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStatement([NotNull] SidlParser.ImportStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>typedefStatement</c>
	/// labeled alternative in <see cref="SidlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedefStatement([NotNull] SidlParser.TypedefStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScope([NotNull] SidlParser.ScopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SidlParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.atomictype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomictype([NotNull] SidlParser.AtomictypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.complextype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplextype([NotNull] SidlParser.ComplextypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.graphtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGraphtype([NotNull] SidlParser.GraphtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] SidlParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.typename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypename([NotNull] SidlParser.TypenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.atomictypeortypename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomictypeortypename([NotNull] SidlParser.AtomictypeortypenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.variablelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariablelist([NotNull] SidlParser.VariablelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.typedvariablelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedvariablelist([NotNull] SidlParser.TypedvariablelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.customtypedvariablelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomtypedvariablelist([NotNull] SidlParser.CustomtypedvariablelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.messageparameterlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageparameterlist([NotNull] SidlParser.MessageparameterlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.messageparametersignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageparametersignature([NotNull] SidlParser.MessageparametersignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.expressionlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionlist([NotNull] SidlParser.ExpressionlistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SidlParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.arraydeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraydeclaration([NotNull] SidlParser.ArraydeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.arrayaccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayaccess([NotNull] SidlParser.ArrayaccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.fieldaccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldaccess([NotNull] SidlParser.FieldaccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.lefthandside"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLefthandside([NotNull] SidlParser.LefthandsideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.importstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportstatement([NotNull] SidlParser.ImportstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.typedefstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedefstatement([NotNull] SidlParser.TypedefstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.functiondefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctiondefinition([NotNull] SidlParser.FunctiondefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.functionbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionbody([NotNull] SidlParser.FunctionbodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.returnstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnstatement([NotNull] SidlParser.ReturnstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctioncall([NotNull] SidlParser.FunctioncallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.structpropertylist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructpropertylist([NotNull] SidlParser.StructpropertylistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.structdefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructdefinition([NotNull] SidlParser.StructdefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.messagetypename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessagetypename([NotNull] SidlParser.MessagetypenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.nodetypename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodetypename([NotNull] SidlParser.NodetypenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.messagetypelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessagetypelist([NotNull] SidlParser.MessagetypelistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.messagedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessagedefinition([NotNull] SidlParser.MessagedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.nodetypedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodetypedefinition([NotNull] SidlParser.NodetypedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.nodetypesignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodetypesignature([NotNull] SidlParser.NodetypesignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.nodedefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodedefinition([NotNull] SidlParser.NodedefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.nodebody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodebody([NotNull] SidlParser.NodebodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.metadefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetadefinition([NotNull] SidlParser.MetadefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] SidlParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] SidlParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] SidlParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SidlParser.terminator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminator([NotNull] SidlParser.TerminatorContext context);
}
} // namespace Sidl.Processor
